//! Spec-hash fingerprinting for incremental code generation.
//!
//! Each generated file embeds a SHA256 hash of the input data.
//! On subsequent runs, files with matching hashes are skipped.

use std::path::Path;

use sha2::{Digest, Sha256};

/// Compute SHA256 hash of serialized data, hex-encoded.
pub(crate) fn compute_spec_hash<T: serde::Serialize>(value: &T) -> String {
    let json = serde_json::to_string(value).unwrap_or_default();
    let mut hasher = Sha256::new();
    hasher.update(json.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// Check if an existing output file has a matching spec-hash in its header.
pub(crate) fn check_spec_hash(output_path: &Path, expected_hash: &str) -> bool {
    let Ok(contents) = std::fs::read_to_string(output_path) else {
        return false;
    };

    let hash_prefix = "// spec-hash: ";
    for line in contents.lines().take(5) {
        if let Some(hash) = line.strip_prefix(hash_prefix) {
            return hash.trim() == expected_hash;
        }
    }
    false
}

/// Build the file header comment with spec-hash.
pub(crate) fn spec_hash_header(hash: &str) -> String {
    format!(
        "// Generated by sysml-v2-analyzer — DO NOT EDIT\n// spec-hash: {hash}\n\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_compute_spec_hash() {
        let data = serde_json::json!({"name": "test", "value": 42});
        let hash1 = compute_spec_hash(&data);
        let hash2 = compute_spec_hash(&data);
        assert_eq!(hash1, hash2, "hash should be deterministic");
        assert_eq!(hash1.len(), 64, "SHA256 hex should be 64 chars");
    }

    #[test]
    fn test_check_spec_hash_match() {
        let tmp = std::env::temp_dir().join(format!("spec-hash-test-{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();
        let file = tmp.join("test.rs");

        let hash = "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890";
        let content = format!(
            "// Generated by sysml-v2-analyzer — DO NOT EDIT\n// spec-hash: {hash}\n\nfn main() {{}}\n"
        );
        std::fs::write(&file, content).unwrap();

        assert!(check_spec_hash(&file, hash));
        assert!(!check_spec_hash(&file, "different_hash"));

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_check_spec_hash_missing_file() {
        assert!(!check_spec_hash(
            &PathBuf::from("/nonexistent/file.rs"),
            "any_hash"
        ));
    }

    #[test]
    fn test_spec_hash_header() {
        let header = spec_hash_header("abc123");
        assert!(header.contains("spec-hash: abc123"));
        assert!(header.contains("DO NOT EDIT"));
    }
}

#[cfg(test)]
mod property_tests {
    use super::*;
    use proptest::prelude::*;

    proptest! {
        #[test]
        fn hash_is_deterministic(s in ".*") {
            let h1 = compute_spec_hash(&s);
            let h2 = compute_spec_hash(&s);
            prop_assert_eq!(h1, h2);
        }

        #[test]
        fn hash_is_64_hex_chars(s in ".*") {
            let h = compute_spec_hash(&s);
            prop_assert_eq!(h.len(), 64, "hash length should be 64, got {}", h.len());
            prop_assert!(
                h.chars().all(|c| c.is_ascii_hexdigit()),
                "hash '{}' contains non-hex chars",
                h,
            );
        }

        #[test]
        fn hash_is_lowercase(s in ".*") {
            let h = compute_spec_hash(&s);
            prop_assert!(
                !h.chars().any(|c| c.is_uppercase()),
                "hash should be lowercase hex",
            );
        }

        #[test]
        fn header_round_trips_through_check(s in "[a-zA-Z0-9]{1,50}") {
            let hash = compute_spec_hash(&s);
            let header = spec_hash_header(&hash);
            let content = format!("{}fn main() {{}}", header);

            let tmp = std::env::temp_dir().join(format!(
                "proptest-hash-{}",
                std::process::id()
            ));
            std::fs::create_dir_all(&tmp).unwrap();
            let file = tmp.join("test.rs");
            std::fs::write(&file, &content).unwrap();

            prop_assert!(
                check_spec_hash(&file, &hash),
                "header round-trip failed for input '{}'",
                s,
            );

            let _ = std::fs::remove_dir_all(&tmp);
        }
    }
}
